### ISSUE TITLE
Generate a pdf using puppeteer

### ISSUE THREAD

**Issue by jigar1101** [jigar1101/puppeteer-demos#3]
https://github.com/GoogleChrome/puppeteer

**Comment by ypahalajani** [comment]
@jigar1101 I'm up for this!

**Comment by jigar1101** [comment]
@ypahalajani Great! Create a new route for it and update the naming conventions of the functions as well.

**Comment by zilehuda** [comment]
On it (Y)

**Comment by jigar1101** [comment]
@zilehuda Unfortunately, @ypahalajani has already taken it up. You can check out some other functionality like simulating form submission

You can check [this](https://github.com/jigar1101/puppeteer-demos/issues/5)
